name: Q2
run-name: ${{ github.actor }} 

on: [push]

permissions:
  contents: write

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Ajout du nom dans le fichier
        run: |
          echo "GUELLE Clément" >> Q2_archive_TOTO.txt
      - name: Ajout de la date d execution
        run: |
          DATE=$(date +"%Y%m%d-%H%M%S")
          echo "DATE=$DATE" >> $GITHUB_ENV
          date >> Q2_archive_TOTO.txt
      - name: Copie du fichier TOTO.txt dans Q2_archive_TOTO.txt
        run: |
          cat TOTO.txt >> Q2_archive_TOTO.txt
      - name: Ajout de la taille du fichier
        run: |
          ls -lh TOTO.txt >> Q2_archive_TOTO.txt
      - name: Commmit et push
        run: |
          git config --global user.name ClementGuelle
          git config --global user.email clement.guelle@etu.univ-lehavre.fr
          git add Q2_archive_TOTO.txt
          git commit -m "Archive du fichier TOTO.txt"
          git push
